apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 340752805670.dkr.ecr.eu-north-1.amazonaws.com/fullstack_blog:frontend
        ports:
        - containerPort: 80
